### ISSUE TITLE
Issue with babel-jest dependency when running starting React App

### ISSUE THREAD

**Issue by yliu0715** [meowl-surveillance-system/meowl#47]
Problem occurs because there is a node_modules folder in the parent directory of the client folder. Need to move client to be on the same level as server.

**Comment by chc5** [comment]
Have you changed the test command to ignore the client directory? I do agree that the client directory shouldn't be in the server directory.

**Comment by yliu0715** [comment]
Yeah, I have a separate test script that runs only the server tests defined, but this problem occurs when trying to start the react server which, after a quick google search, seems to be caused by the node_modules/babel-jest and node_modules/jest that exist in both the client folder and the server folder. https://stackoverflow.com/questions/53089122/issue-with-babel-jest-dependency-when-running-npm-start-in-a-react-app/53399561#53399561
